<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Votre Nom">
<meta name="dcterms.date" content="2026-04-29">

<title>Les crèches favorisent-elles la natalité ? Une analyse départementale en France (2017–2023)</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="homework-6_files/libs/clipboard/clipboard.min.js"></script>
<script src="homework-6_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="homework-6_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="homework-6_files/libs/quarto-html/popper.min.js"></script>
<script src="homework-6_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="homework-6_files/libs/quarto-html/anchor.min.js"></script>
<link href="homework-6_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="homework-6_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="homework-6_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="homework-6_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="homework-6_files/libs/bootstrap/bootstrap-de9ea4695b5809f5b49b6072e50bb385.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="homework-6_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="homework-6_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#revue-de-littérature" id="toc-revue-de-littérature" class="nav-link" data-scroll-target="#revue-de-littérature"><span class="header-section-number">1.1</span> Revue de littérature</a></li>
  <li><a href="#contribution-de-ce-travail" id="toc-contribution-de-ce-travail" class="nav-link" data-scroll-target="#contribution-de-ce-travail"><span class="header-section-number">1.2</span> Contribution de ce travail</a></li>
  </ul></li>
  <li><a href="#données" id="toc-données" class="nav-link" data-scroll-target="#données"><span class="header-section-number">2</span> Données</a>
  <ul class="collapse">
  <li><a href="#taux-de-couverture-petite-enfance-cnaf" id="toc-taux-de-couverture-petite-enfance-cnaf" class="nav-link" data-scroll-target="#taux-de-couverture-petite-enfance-cnaf"><span class="header-section-number">2.1</span> Taux de couverture petite enfance (CNAF)</a></li>
  <li><a href="#taux-de-natalité-insee" id="toc-taux-de-natalité-insee" class="nav-link" data-scroll-target="#taux-de-natalité-insee"><span class="header-section-number">2.2</span> Taux de natalité (INSEE)</a></li>
  <li><a href="#indice-demploi-relatif-insee" id="toc-indice-demploi-relatif-insee" class="nav-link" data-scroll-target="#indice-demploi-relatif-insee"><span class="header-section-number">2.3</span> Indice d’emploi relatif (INSEE)</a></li>
  <li><a href="#fusion-des-trois-sources-et-base-finale" id="toc-fusion-des-trois-sources-et-base-finale" class="nav-link" data-scroll-target="#fusion-des-trois-sources-et-base-finale"><span class="header-section-number">2.4</span> Fusion des trois sources et base finale</a></li>
  </ul></li>
  <li><a href="#statistiques-descriptives-et-analyse-exploratoire" id="toc-statistiques-descriptives-et-analyse-exploratoire" class="nav-link" data-scroll-target="#statistiques-descriptives-et-analyse-exploratoire"><span class="header-section-number">3</span> Statistiques descriptives et analyse exploratoire</a>
  <ul class="collapse">
  <li><a href="#tableau-de-statistiques-descriptives" id="toc-tableau-de-statistiques-descriptives" class="nav-link" data-scroll-target="#tableau-de-statistiques-descriptives"><span class="header-section-number">3.1</span> Tableau de statistiques descriptives</a></li>
  <li><a href="#distribution-du-taux-de-natalité" id="toc-distribution-du-taux-de-natalité" class="nav-link" data-scroll-target="#distribution-du-taux-de-natalité"><span class="header-section-number">3.2</span> Distribution du taux de natalité</a></li>
  <li><a href="#carte-du-taux-de-natalité-en-2023" id="toc-carte-du-taux-de-natalité-en-2023" class="nav-link" data-scroll-target="#carte-du-taux-de-natalité-en-2023"><span class="header-section-number">3.3</span> Carte du taux de natalité en 2023</a></li>
  </ul></li>
  <li><a href="#fusion-des-deux-polygones-rhône-en-un-seul" id="toc-fusion-des-deux-polygones-rhône-en-un-seul" class="nav-link" data-scroll-target="#fusion-des-deux-polygones-rhône-en-un-seul"><span class="header-section-number">4</span> Fusion des deux polygones Rhône en un seul</a></li>
  <li><a href="#jointure-avec-les-données-2023" id="toc-jointure-avec-les-données-2023" class="nav-link" data-scroll-target="#jointure-avec-les-données-2023"><span class="header-section-number">5</span> Jointure avec les données 2023</a>
  <ul class="collapse">
  <li><a href="#carte-du-taux-de-couverture-petite-enfance-en-2023" id="toc-carte-du-taux-de-couverture-petite-enfance-en-2023" class="nav-link" data-scroll-target="#carte-du-taux-de-couverture-petite-enfance-en-2023"><span class="header-section-number">5.1</span> Carte du taux de couverture petite enfance en 2023</a></li>
  <li><a href="#accueil-collectif-versus-accueil-individuel" id="toc-accueil-collectif-versus-accueil-individuel" class="nav-link" data-scroll-target="#accueil-collectif-versus-accueil-individuel"><span class="header-section-number">5.2</span> Accueil collectif versus accueil individuel</a></li>
  <li><a href="#corrélation-préliminaire-natalité-et-couverture" id="toc-corrélation-préliminaire-natalité-et-couverture" class="nav-link" data-scroll-target="#corrélation-préliminaire-natalité-et-couverture"><span class="header-section-number">5.3</span> Corrélation préliminaire : natalité et couverture</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="homework-6.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Les crèches favorisent-elles la natalité ? Une analyse départementale en France (2017–2023)</h1>
<p class="subtitle lead">Introduction à l’Économétrie et à R</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Votre Nom </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 29, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>La France fait face à un déclin démographique inédit. Son taux de natalité est passé de 12,6 naissances pour 1 000 habitants en 2010 à environ 10,6 en 2017, puis à 9,9 en 2023. Le rapport annuel de l’INED sur la conjoncture démographique (2025) enregistre pour la première fois depuis un siècle une <strong>croissance naturelle nulle dans l’Hexagone</strong>. Ce constat suscite un débat de politique publique croissant autour des leviers susceptibles de soutenir la fécondité des ménages.</p>
<p>Parmi ces leviers, le développement des structures d’accueil du jeune enfant (EAJE — crèches, halte-garderies, micro-crèches) occupe une place centrale dans les propositions récentes. L’intuition économique est directe : des modes de garde accessibles réduisent le coût d’opportunité de la maternité pour les femmes actives, facilitent la conciliation entre vie professionnelle et parentalité, et devraient ainsi encourager les naissances. Cette logique se retrouve dans plusieurs recommandations institutionnelles : l’Académie nationale de médecine place en deuxième position de ses préconisations la création de 100 000 places de crèches d’ici 2030 avec un financement pérenne de l’État et des CAF. Dans la même veine, Elsa Hervy, déléguée générale de la Fédération française des entreprises de crèches, défend cette orientation dans un article de la revue <em>Administration</em> (2025).</p>
<section id="revue-de-littérature" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="revue-de-littérature"><span class="header-section-number">1.1</span> Revue de littérature</h2>
<p><strong>À l’international</strong>, la relation entre l’offre de garde formelle et la fécondité est documentée dans de nombreux pays, avec des résultats majoritairement positifs. Les études les plus robustes ont été conduites en contexte nordique. Rindfuss, Guilkey et Morgan (2010) exploitent une réforme d’ampleur en Norvège pour identifier une variation <strong>exogène</strong> de l’offre de places et montrent un effet positif et significatif sur la fécondité. Dans le même esprit, Mörk, Sjögren et Svaleryd (2013) tirent parti d’une réforme suédoise sur le prix des crèches pour établir un lien causal entre coût de la garde et décisions de fécondité.</p>
<p>En Allemagne, Hener, Bauernschuster et Rainer (2013) mobilisent une stratégie de <strong>double différence</strong> dans un contexte particulièrement favorable à l’identification : l’ex-Allemagne de l’Est était largement dépourvue de places en crèche jusqu’au début des années 2000, et la mise en œuvre des politiques d’expansion a varié fortement d’un <em>Kreis</em> à l’autre, créant une variation locale exploitable. Leur étude confirme un effet positif de l’augmentation de l’offre sur la natalité, avec une hétérogénéité marquée selon l’ampleur de l’expansion locale.</p>
<p>Plus généralement, des résultats convergents ont été obtenus au Japon, en Corée du Sud et en Espagne — à l’exception notable d’un cas espagnol où les crèches privées sont associées à une relation négative avec la natalité, suggérant que les caractéristiques de l’offre (public vs.&nbsp;privé, tarification) importent autant que son volume. Luci-Greulich et Thévenon (2013), dans une étude portant sur 18 pays de l’OCDE, montrent que les services d’accueil pour les enfants de moins de trois ans exercent un effet potentiellement plus important sur la fécondité que les congés parentaux ou les transferts financiers à la naissance.</p>
<p><strong>En France</strong>, ce lien n’a, à notre connaissance, pas encore fait l’objet d’une estimation causale directe au niveau infranational, ce qui explique que les rapports institutionnels cités plus haut n’appuient pas leurs recommandations sur une étude empirique française. Une analyse de l’INSEE (2020) a certes montré qu’accroître l’offre de places en crèche avait peu d’effet sur l’emploi des mères, tout en réduisant le recours aux autres modes de garde — mais la question de l’effet sur la natalité reste ouverte.</p>
</section>
<section id="contribution-de-ce-travail" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="contribution-de-ce-travail"><span class="header-section-number">1.2</span> Contribution de ce travail</h2>
<p>Ce travail propose une première approche empirique de cette question à l’échelle des 96 départements métropolitains français, pour les années <strong>2017</strong> et <strong>2023</strong>. En mobilisant les données CNAF sur les taux de couverture petite enfance et les statistiques d’état civil de l’INSEE, nous tentons d’évaluer si l’évolution de l’offre d’accueil est associée à une évolution du taux de natalité. Si la méthode retenue — une approche en double différence — est plus simple que les stratégies d’identification exploitées dans les études nordiques ou allemandes, et demeure exposée à certains problèmes d’endogénéité, elle constitue un point de départ rigoureux pour documenter ce lien dans le contexte français.</p>
<hr>
</section>
</section>
<section id="données" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Données</h1>
<p>La base de données mobilisée dans cette étude est construite par appariement de trois sources statistiques publiques portant sur les <strong>96 départements métropolitains</strong> pour les années <strong>2017</strong> et <strong>2023</strong> : les données de couverture petite enfance (CNAF), les statistiques de naissances et de population (INSEE), et les données d’emploi salarié départemental (INSEE). Les DROM-COM sont exclus : leurs caractéristiques structurelles sont trop éloignées de celles des départements métropolitains et leurs valeurs atypiques de natalité biaiseraient les estimations.</p>
<p>Tous les identifiants géographiques sont harmonisés sous forme de chaîne de caractères afin de traiter correctement les codes <code>2A</code> et <code>2B</code> lors des fusions.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Codes des 96 départements métropolitains</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>codes_metro <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">sprintf</span>(<span class="st">"%02d"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">19</span>), <span class="st">"2A"</span>, <span class="st">"2B"</span>, <span class="fu">as.character</span>(<span class="dv">21</span><span class="sc">:</span><span class="dv">95</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="taux-de-couverture-petite-enfance-cnaf" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="taux-de-couverture-petite-enfance-cnaf"><span class="header-section-number">2.1</span> Taux de couverture petite enfance (CNAF)</h2>
<p>Les données de couverture sont issues de deux fichiers de la CNAF : <code>txcouv_pe_dep_hist.csv</code> pour les années antérieures à 2022 (qui contient donc 2017), et <code>txcouv_pe_dep.csv</code> pour 2022-2023. Chacun est filtré sur les départements métropolitains, puis les années 2017 et 2023 sont extraites séparément.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chargement et filtrage sur la métropole</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>crechedep2223 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"txcouv_pe_dep.csv"</span>,      <span class="at">sep =</span> <span class="st">";"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Numéro.Département <span class="sc">%in%</span> codes_metro)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>crechedep1722 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"txcouv_pe_dep_hist.csv"</span>, <span class="at">sep =</span> <span class="st">";"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Numéro.Département <span class="sc">%in%</span> codes_metro)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Extraction des années cibles et sélection des variables utiles</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>vars_couv <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Date.référence"</span>, <span class="st">"Numéro.Département"</span>, <span class="st">"Nom.Département"</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Taux.de.couv.EAJE.PSU"</span>, <span class="st">"Taux.de.couv.hors.EAJE.PSU"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Taux.de.couv.EAJE...ensemble"</span>, <span class="st">"Taux.de.couv.préscolarisation"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Taux.de.couv.assistante.maternelle"</span>, <span class="st">"Taux.de.couv.salariée.à.domicile"</span>,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Taux.de.couv.accueil.individuel...ensemble"</span>, <span class="st">"Taux.de.couv.global"</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>noms_couv <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"année"</span>, <span class="st">"Code.de.département"</span>, <span class="st">"département"</span>,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Taux.de.couv.EAJE.PSU"</span>, <span class="st">"Taux.de.couv.hors.EAJE.PSU"</span>,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Taux.de.couv.EAJE...ensemble"</span>, <span class="st">"Taux.de.couv.préscolarisation"</span>,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Taux.de.couv.assistante.maternelle"</span>, <span class="st">"Taux.de.couv.salariée.à.domicile"</span>,</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Taux.de.couv.accueil.individuel...ensemble"</span>, <span class="st">"Taux.de.couv.global"</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>crechedep17 <span class="ot">&lt;-</span> crechedep1722 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Date.référence <span class="sc">==</span> <span class="dv">2017</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(vars_couv)) <span class="sc">|&gt;</span> <span class="fu">setNames</span>(noms_couv)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>crechedep23 <span class="ot">&lt;-</span> crechedep2223 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Date.référence <span class="sc">==</span> <span class="dv">2023</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(vars_couv)) <span class="sc">|&gt;</span> <span class="fu">setNames</span>(noms_couv)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Le <strong>taux de couverture</strong> mesure la capacité d’accueil théorique pour 100 enfants de moins de 3 ans dans un département. Il se décompose en plusieurs modes d’accueil :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Mode</th>
<th>Variable</th>
<th>Nature</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>EAJE PSU</td>
<td><code>Taux.de.couv.EAJE.PSU</code></td>
<td>Crèches collectives, halte-garderies (financement CAF-PSU)</td>
</tr>
<tr class="even">
<td>Hors PSU</td>
<td><code>Taux.de.couv.hors.EAJE.PSU</code></td>
<td>Micro-crèches PAJE</td>
</tr>
<tr class="odd">
<td>Préscolarisation</td>
<td><code>Taux.de.couv.préscolarisation</code></td>
<td>Enfants &lt; 3 ans en maternelle</td>
</tr>
<tr class="even">
<td>Assistante maternelle</td>
<td><code>Taux.de.couv.assistante.maternelle</code></td>
<td>Accueil individuel agréé</td>
</tr>
<tr class="odd">
<td>Salariée à domicile</td>
<td><code>Taux.de.couv.salariée.à.domicile</code></td>
<td>Garde au domicile</td>
</tr>
<tr class="even">
<td><strong>Global</strong></td>
<td><code>Taux.de.couv.global</code></td>
<td>Agrégat de tous les modes</td>
</tr>
</tbody>
</table>
<p>Pour l’estimation, on construit deux variables synthétiques selon la nature de l’accueil. L’accueil <strong>collectif</strong> regroupe les structures relevant principalement de décisions publiques d’investissement ; l’accueil <strong>individuel</strong> dépend davantage du marché local et des préférences des familles. Cette distinction permet de tester si l’effet sur la natalité diffère selon le type de garde.</p>
<p><span class="math display">\[\text{Couverture collective} = \text{EAJE PSU} + \text{Hors EAJE PSU} + \text{Préscolarisation}\]</span> <span class="math display">\[\text{Couverture individuelle} = \text{Assistante maternelle} + \text{Salariée à domicile}\]</span></p>
<p>Les virgules décimales présentes dans les fichiers bruts CNAF sont remplacées par des points (<code>gsub(",", ".", .)</code>) avant toute conversion numérique.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Conversion numérique et construction des agrégats collectif / individuel</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>construire_taux_couv <span class="ot">&lt;-</span> <span class="cf">function</span>(df) {</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">|&gt;</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>      Code.de.département <span class="ot">=</span> <span class="fu">as.character</span>(Code.de.département),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"Taux"</span>), <span class="sc">~</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, .))),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">Taux.de.couv.collectif  =</span> Taux.de.couv.EAJE.PSU <span class="sc">+</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                                 Taux.de.couv.hors.EAJE.PSU <span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>                                 Taux.de.couv.préscolarisation,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">Taux.de.couv.individuel =</span> Taux.de.couv.assistante.maternelle <span class="sc">+</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                                 Taux.de.couv.salariée.à.domicile</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>crechedep17 <span class="ot">&lt;-</span> <span class="fu">construire_taux_couv</span>(crechedep17)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>crechedep23 <span class="ot">&lt;-</span> <span class="fu">construire_taux_couv</span>(crechedep23)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="taux-de-natalité-insee" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="taux-de-natalité-insee"><span class="header-section-number">2.2</span> Taux de natalité (INSEE)</h2>
<p>Les données de naissances sont issues du tableau N1D de l’INSEE (état civil). Après suppression des lignes d’en-tête, les naissances sont appariées aux populations départementales issues du recensement. Un tableau de correspondance (<code>codes_dep</code>) permet d’associer le nom de département tel que fourni par l’INSEE au code officiel.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Table de correspondance nom → code département</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>codes_dep <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  Code.de.département <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"01"</span>,<span class="st">"02"</span>,<span class="st">"03"</span>,<span class="st">"04"</span>,<span class="st">"05"</span>,<span class="st">"06"</span>,<span class="st">"07"</span>,<span class="st">"08"</span>,<span class="st">"09"</span>,<span class="st">"10"</span>,<span class="st">"11"</span>,<span class="st">"12"</span>,<span class="st">"13"</span>,<span class="st">"14"</span>,<span class="st">"15"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"16"</span>,<span class="st">"17"</span>,<span class="st">"18"</span>,<span class="st">"19"</span>,<span class="st">"21"</span>,<span class="st">"22"</span>,<span class="st">"23"</span>,<span class="st">"24"</span>,<span class="st">"25"</span>,<span class="st">"26"</span>,<span class="st">"27"</span>,<span class="st">"28"</span>,<span class="st">"29"</span>,<span class="st">"2A"</span>,<span class="st">"2B"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"30"</span>,<span class="st">"31"</span>,<span class="st">"32"</span>,<span class="st">"33"</span>,<span class="st">"34"</span>,<span class="st">"35"</span>,<span class="st">"36"</span>,<span class="st">"37"</span>,<span class="st">"38"</span>,<span class="st">"39"</span>,<span class="st">"40"</span>,<span class="st">"41"</span>,<span class="st">"42"</span>,<span class="st">"43"</span>,<span class="st">"44"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"45"</span>,<span class="st">"46"</span>,<span class="st">"47"</span>,<span class="st">"48"</span>,<span class="st">"49"</span>,<span class="st">"50"</span>,<span class="st">"51"</span>,<span class="st">"52"</span>,<span class="st">"53"</span>,<span class="st">"54"</span>,<span class="st">"55"</span>,<span class="st">"56"</span>,<span class="st">"57"</span>,<span class="st">"58"</span>,<span class="st">"59"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"60"</span>,<span class="st">"61"</span>,<span class="st">"62"</span>,<span class="st">"63"</span>,<span class="st">"64"</span>,<span class="st">"65"</span>,<span class="st">"66"</span>,<span class="st">"67"</span>,<span class="st">"68"</span>,<span class="st">"69"</span>,<span class="st">"70"</span>,<span class="st">"71"</span>,<span class="st">"72"</span>,<span class="st">"73"</span>,<span class="st">"74"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"75"</span>,<span class="st">"76"</span>,<span class="st">"77"</span>,<span class="st">"78"</span>,<span class="st">"79"</span>,<span class="st">"80"</span>,<span class="st">"81"</span>,<span class="st">"82"</span>,<span class="st">"83"</span>,<span class="st">"84"</span>,<span class="st">"85"</span>,<span class="st">"86"</span>,<span class="st">"87"</span>,<span class="st">"88"</span>,<span class="st">"89"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"90"</span>,<span class="st">"91"</span>,<span class="st">"92"</span>,<span class="st">"93"</span>,<span class="st">"94"</span>,<span class="st">"95"</span>),</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  département <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Ain"</span>,<span class="st">"Aisne"</span>,<span class="st">"Allier"</span>,<span class="st">"Alpes-de-Haute-Provence"</span>,<span class="st">"Hautes-Alpes"</span>,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Alpes-Maritimes"</span>,<span class="st">"Ardèche"</span>,<span class="st">"Ardennes"</span>,<span class="st">"Ariège"</span>,<span class="st">"Aube"</span>,<span class="st">"Aude"</span>,<span class="st">"Aveyron"</span>,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Bouches-du-Rhône"</span>,<span class="st">"Calvados"</span>,<span class="st">"Cantal"</span>,<span class="st">"Charente"</span>,<span class="st">"Charente-Maritime"</span>,<span class="st">"Cher"</span>,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Corrèze"</span>,<span class="st">"Côte-d'Or"</span>,<span class="st">"Côtes-d'Armor"</span>,<span class="st">"Creuse"</span>,<span class="st">"Dordogne"</span>,<span class="st">"Doubs"</span>,<span class="st">"Drôme"</span>,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Eure"</span>,<span class="st">"Eure-et-Loir"</span>,<span class="st">"Finistère"</span>,<span class="st">"Corse-du-Sud"</span>,<span class="st">"Haute-Corse"</span>,<span class="st">"Gard"</span>,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Haute-Garonne"</span>,<span class="st">"Gers"</span>,<span class="st">"Gironde"</span>,<span class="st">"Hérault"</span>,<span class="st">"Ille-et-Vilaine"</span>,<span class="st">"Indre"</span>,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Indre-et-Loire"</span>,<span class="st">"Isère"</span>,<span class="st">"Jura"</span>,<span class="st">"Landes"</span>,<span class="st">"Loir-et-Cher"</span>,<span class="st">"Loire"</span>,</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Haute-Loire"</span>,<span class="st">"Loire-Atlantique"</span>,<span class="st">"Loiret"</span>,<span class="st">"Lot"</span>,<span class="st">"Lot-et-Garonne"</span>,<span class="st">"Lozère"</span>,</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Maine-et-Loire"</span>,<span class="st">"Manche"</span>,<span class="st">"Marne"</span>,<span class="st">"Haute-Marne"</span>,<span class="st">"Mayenne"</span>,</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Meurthe-et-Moselle"</span>,<span class="st">"Meuse"</span>,<span class="st">"Morbihan"</span>,<span class="st">"Moselle"</span>,<span class="st">"Nièvre"</span>,<span class="st">"Nord"</span>,<span class="st">"Oise"</span>,</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Orne"</span>,<span class="st">"Pas-de-Calais"</span>,<span class="st">"Puy-de-Dôme"</span>,<span class="st">"Pyrénées-Atlantiques"</span>,</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Hautes-Pyrénées"</span>,<span class="st">"Pyrénées-Orientales"</span>,<span class="st">"Bas-Rhin"</span>,<span class="st">"Haut-Rhin"</span>,<span class="st">"Rhône"</span>,</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Haute-Saône"</span>,<span class="st">"Saône-et-Loire"</span>,<span class="st">"Sarthe"</span>,<span class="st">"Savoie"</span>,<span class="st">"Haute-Savoie"</span>,<span class="st">"Paris"</span>,</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Seine-Maritime"</span>,<span class="st">"Seine-et-Marne"</span>,<span class="st">"Yvelines"</span>,<span class="st">"Deux-Sèvres"</span>,<span class="st">"Somme"</span>,<span class="st">"Tarn"</span>,</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Tarn-et-Garonne"</span>,<span class="st">"Var"</span>,<span class="st">"Vaucluse"</span>,<span class="st">"Vendée"</span>,<span class="st">"Vienne"</span>,<span class="st">"Haute-Vienne"</span>,</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Vosges"</span>,<span class="st">"Yonne"</span>,<span class="st">"Territoire de Belfort"</span>,<span class="st">"Essonne"</span>,<span class="st">"Hauts-de-Seine"</span>,</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Seine-Saint-Denis"</span>,<span class="st">"Val-de-Marne"</span>,<span class="st">"Val-d'Oise"</span>)</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Chargement, nettoyage et appariement des naissances</span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>charger_naissances <span class="ot">&lt;-</span> <span class="cf">function</span>(fichier, <span class="at">ext =</span> <span class="st">"xlsx"</span>) {</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>  lire <span class="ot">&lt;-</span> <span class="cf">if</span> (ext <span class="sc">==</span> <span class="st">"xls"</span>) read_xls <span class="cf">else</span> read_xlsx</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lire</span>(fichier) <span class="sc">|&gt;</span></span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>    <span class="fu">slice</span>(<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)) <span class="sc">|&gt;</span></span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>    <span class="fu">setNames</span>(<span class="fu">c</span>(<span class="st">"département"</span>, <span class="st">"naissances"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>    <span class="fu">merge</span>(codes_dep, <span class="at">by =</span> <span class="st">"département"</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Code.de.département),</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>           Code.de.département <span class="sc">%in%</span> codes_metro)</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>tauxdenatalite17 <span class="ot">&lt;-</span> <span class="fu">charger_naissances</span>(<span class="st">"N1D.xls"</span>,  <span class="at">ext =</span> <span class="st">"xls"</span>)</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>tauxdenatalite23 <span class="ot">&lt;-</span> <span class="fu">charger_naissances</span>(<span class="st">"irsocsd2023_dd9_xlsx/n1d.xlsx"</span>, <span class="at">ext =</span> <span class="st">"xlsx"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Les populations départementales sont extraites des fichiers de recensement (onglet “Départements”). Seules les colonnes d’identification et d’effectif total sont conservées ; les colonnes intermédiaires sont supprimées.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>charger_population <span class="ot">&lt;-</span> <span class="cf">function</span>(fichier, <span class="at">ext =</span> <span class="st">"xlsx"</span>) {</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  lire <span class="ot">&lt;-</span> <span class="cf">if</span> (ext <span class="sc">==</span> <span class="st">"xls"</span>) read_xls <span class="cf">else</span> read_xlsx</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lire</span>(fichier, <span class="at">sheet =</span> <span class="st">"Départements"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">setNames</span>(<span class="fu">c</span>(<span class="st">"a"</span>,<span class="st">"b"</span>,<span class="st">"Code.de.département"</span>,<span class="st">"département"</span>,<span class="st">"d"</span>,<span class="st">"e"</span>,<span class="st">"f"</span>,<span class="st">"g"</span>,<span class="st">"population"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(Code.de.département, département, population) <span class="sc">|&gt;</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">slice</span>(<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(Code.de.département <span class="sc">%in%</span> codes_metro)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>population17 <span class="ot">&lt;-</span> <span class="fu">charger_population</span>(<span class="st">"ensemble.xls"</span>, <span class="at">ext =</span> <span class="st">"xls"</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>population23 <span class="ot">&lt;-</span> <span class="fu">charger_population</span>(<span class="st">"ensemble.xlsx"</span>, <span class="at">ext =</span> <span class="st">"xlsx"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Le taux de natalité est ensuite calculé selon la formule :</p>
<p><span class="math display">\[\text{Taux de natalité}_{d,t} = \frac{\text{Naissances}_{d,t}}{\text{Population}_{d,t}} \times 1000\]</span></p>
<p>Les espaces insécables utilisés comme séparateurs de milliers dans les fichiers bruts sont supprimés avec <code>gsub</code> avant conversion numérique.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>calculer_taux_nat <span class="ot">&lt;-</span> <span class="cf">function</span>(naissances_df, population_df, nom_var) {</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">merge</span>(naissances_df, population_df, <span class="at">by =</span> <span class="st">"Code.de.département"</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">naissances =</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"[ ,]"</span>, <span class="st">""</span>, naissances)),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">population =</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"[ ,]"</span>, <span class="st">""</span>, population)),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>      <span class="sc">!!</span><span class="at">nom_var  :=</span> (naissances <span class="sc">/</span> population) <span class="sc">*</span> <span class="dv">1000</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>      Code.de.département <span class="ot">=</span> <span class="fu">as.character</span>(Code.de.département)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(Code.de.département, naissances, population, <span class="sc">!!</span><span class="fu">sym</span>(nom_var))</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>taux17 <span class="ot">&lt;-</span> <span class="fu">calculer_taux_nat</span>(tauxdenatalite17, population17, <span class="st">"taux_natalite_2017"</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>taux23 <span class="ot">&lt;-</span> <span class="fu">calculer_taux_nat</span>(tauxdenatalite23, population23, <span class="st">"taux_natalite_2023"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>On peut vérifier la plausibilité des valeurs : le taux moyen sur les 96 départements métropolitains est de <strong>9.93 ‰</strong> en 2017 et <strong>8.58 ‰</strong> en 2023, cohérents avec les taux nationaux publiés par l’INSEE (qui incluent également les DROM, légèrement plus élevés).</p>
</section>
<section id="indice-demploi-relatif-insee" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="indice-demploi-relatif-insee"><span class="header-section-number">2.3</span> Indice d’emploi relatif (INSEE)</h2>
<p>Les données d’emploi salarié sont issues du tableau longitudinal T201 de l’INSEE. Après suppression des lignes d’en-tête et filtrage des entités non départementales, seules les colonnes 2017 et 2023 sont conservées.</p>
<p>Le marché du travail local est une variable confondante incontournable : un département économiquement dynamique attire des actifs en âge de procréer, ce qui peut simultanément accroître la demande de crèches et le taux de natalité. Omettre cette variable conduirait à surestimer l’effet propre des crèches.</p>
<p>On construit un <strong>indice d’emploi relatif</strong> en normalisant le taux d’emploi brut de chaque département par le taux d’emploi national :</p>
<p><span class="math display">\[\text{Indice d'emploi}_{d,t} = \frac{\text{Emplois}_{d,t} / \text{Population}_{d,t}}{\displaystyle\sum_d \text{Emplois}_{d,t} \big/ \sum_d \text{Population}_{d,t}} \times 100\]</span></p>
<p>Un indice de 100 correspond à la moyenne nationale. Les valeurs supérieures à 100 indiquent une densité d’emploi supérieure à la moyenne (Paris, Hauts-de-Seine) ; inférieures à 100, une économie locale moins dense (départements ruraux).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>emploi_raw <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"t201.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ENS - T"</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Renommer les colonnes années</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(emploi_raw) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"département"</span>, <span class="fu">as.character</span>(<span class="dv">1989</span><span class="sc">:</span><span class="dv">2023</span>))</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Extraire le code département (avant le tiret) et filtrer sur la métropole</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>emploi_raw <span class="ot">&lt;-</span> emploi_raw <span class="sc">|&gt;</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(Code.de.département <span class="ot">=</span> <span class="fu">sub</span>(<span class="st">"-.*"</span>, <span class="st">""</span>, département)) <span class="sc">|&gt;</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">"^(0[1-9]|[1-9][0-9]|2A|2B)$"</span>, Code.de.département))</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Fonction : jointure emploi + population → indice relatif</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>construire_indice_emploi <span class="ot">&lt;-</span> <span class="cf">function</span>(emploi_df, population_df, annee) {</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  emploi_df <span class="sc">|&gt;</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(Code.de.département, département, <span class="at">emplois =</span> <span class="fu">all_of</span>(annee)) <span class="sc">|&gt;</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">left_join</span>(population_df, <span class="at">by =</span> <span class="st">"Code.de.département"</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">emplois    =</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"[ ,]"</span>, <span class="st">""</span>, emplois)),</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">population =</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"[ ,]"</span>, <span class="st">""</span>, population))</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">taux_france   =</span> <span class="fu">sum</span>(emplois, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">sum</span>(population, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">indice_emploi =</span> (emplois <span class="sc">/</span> population) <span class="sc">/</span> taux_france <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>      Code.de.département <span class="ot">=</span> <span class="fu">as.character</span>(Code.de.département)</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(Code.de.département, emplois, population, indice_emploi)</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>base17 <span class="ot">&lt;-</span> <span class="fu">construire_indice_emploi</span>(emploi_raw, population17, <span class="st">"2017"</span>)</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>base23 <span class="ot">&lt;-</span> <span class="fu">construire_indice_emploi</span>(emploi_raw, population23, <span class="st">"2023"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="fusion-des-trois-sources-et-base-finale" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="fusion-des-trois-sources-et-base-finale"><span class="header-section-number">2.4</span> Fusion des trois sources et base finale</h2>
<p>Les trois sources sont appariées par <code>Code.de.département</code>. Les colonnes redondantes issues des fusions (libellés géographiques dupliqués, colonnes intermédiaires) sont supprimées. Les variables synthétiques de couverture collective et individuelle étant déjà construites, la base finale est prête pour l’estimation.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>fusionner <span class="ot">&lt;-</span> <span class="cf">function</span>(couv, taux_nat, emploi) {</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">merge</span>(couv,     taux_nat, <span class="at">by =</span> <span class="st">"Code.de.département"</span>, <span class="at">all =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">merge</span>(emploi,             <span class="at">by =</span> <span class="st">"Code.de.département"</span>, <span class="at">all =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">matches</span>(<span class="st">"département</span><span class="sc">\\</span><span class="st">.[xy]|population</span><span class="sc">\\</span><span class="st">.x|^année$"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Taux.de.couv.EAJE.PSU)) <span class="sc">|&gt;</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(Code.de.département, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>final17 <span class="ot">&lt;-</span> <span class="fu">fusionner</span>(crechedep17, taux17, base17)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>final23 <span class="ot">&lt;-</span> <span class="fu">fusionner</span>(crechedep23, taux23, base23)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>On vérifie les dimensions et la cohérence interne : la somme des couvertures collective et individuelle construites doit être proche du taux global fourni directement par la CNAF. Des écarts résiduels mineurs peuvent exister en raison d’arrondis dans les fichiers sources.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Dimensions — final17 :"</span>, <span class="fu">nrow</span>(final17), <span class="st">"×"</span>, <span class="fu">ncol</span>(final17),</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | final23 :"</span>, <span class="fu">nrow</span>(final23), <span class="st">"×"</span>, <span class="fu">ncol</span>(final23), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Dimensions — final17 : 96 × 17  | final23 : 96 × 17 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>final17 <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ecart =</span> <span class="fu">abs</span>((Taux.de.couv.collectif <span class="sc">+</span> Taux.de.couv.individuel) <span class="sc">-</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                      Taux.de.couv.global)) <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">`</span><span class="at">Écart moyen (pts)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(ecart, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">3</span>),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Écart max (pts)</span><span class="st">`</span>   <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">max</span>(ecart,  <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">3</span>)) <span class="sc">|&gt;</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Cohérence interne : collectif + individuel vs. taux global — 2017"</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>, <span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="table table-striped caption-top table-sm small">
<caption>Cohérence interne : collectif + individuel vs. taux global — 2017</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Écart moyen (pts)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Écart max (pts)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.051</td>
<td style="text-align: right;">0.2</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>final17 <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Code.de.département, département, taux_natalite_2017,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>         Taux.de.couv.global, Taux.de.couv.collectif,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>         Taux.de.couv.individuel, indice_emploi) <span class="sc">|&gt;</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">6</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">round</span>(., <span class="dv">2</span>))) <span class="sc">|&gt;</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Aperçu de la base 2017 — variables retenues pour l'estimation"</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"condensed"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<caption>Aperçu de la base 2017 — variables retenues pour l'estimation</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Code.de.département</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">département</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">taux_natalite_2017</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Taux.de.couv.global</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Taux.de.couv.collectif</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Taux.de.couv.individuel</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">indice_emploi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;">AIN</td>
<td style="text-align: right;">10.54</td>
<td style="text-align: right;">66.4</td>
<td style="text-align: right;">16.7</td>
<td style="text-align: right;">49.6</td>
<td style="text-align: right;">81.83</td>
</tr>
<tr class="even">
<td style="text-align: left;">02</td>
<td style="text-align: left;">AISNE</td>
<td style="text-align: right;">10.78</td>
<td style="text-align: right;">56.1</td>
<td style="text-align: right;">14.6</td>
<td style="text-align: right;">41.6</td>
<td style="text-align: right;">76.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">03</td>
<td style="text-align: left;">ALLIER</td>
<td style="text-align: right;">8.29</td>
<td style="text-align: right;">64.6</td>
<td style="text-align: right;">17.4</td>
<td style="text-align: right;">47.2</td>
<td style="text-align: right;">86.57</td>
</tr>
<tr class="even">
<td style="text-align: left;">04</td>
<td style="text-align: left;">ALPES DE HAUTE PROVENCE</td>
<td style="text-align: right;">8.59</td>
<td style="text-align: right;">51.7</td>
<td style="text-align: right;">28.3</td>
<td style="text-align: right;">23.4</td>
<td style="text-align: right;">87.90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">05</td>
<td style="text-align: left;">HAUTES ALPES</td>
<td style="text-align: right;">8.33</td>
<td style="text-align: right;">61.5</td>
<td style="text-align: right;">30.6</td>
<td style="text-align: right;">30.9</td>
<td style="text-align: right;">100.48</td>
</tr>
<tr class="even">
<td style="text-align: left;">06</td>
<td style="text-align: left;">ALPES MARITIMES</td>
<td style="text-align: right;">10.83</td>
<td style="text-align: right;">49.2</td>
<td style="text-align: right;">28.2</td>
<td style="text-align: right;">21.0</td>
<td style="text-align: right;">102.59</td>
</tr>
</tbody>
</table>
</div>
</div>
<hr>
</section>
</section>
<section id="statistiques-descriptives-et-analyse-exploratoire" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Statistiques descriptives et analyse exploratoire</h1>
<section id="tableau-de-statistiques-descriptives" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="tableau-de-statistiques-descriptives"><span class="header-section-number">3.1</span> Tableau de statistiques descriptives</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>stats_desc <span class="ot">&lt;-</span> <span class="cf">function</span>(df, annee, var_natalite) {</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>      Année                <span class="ot">=</span> annee,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Moy. natalité</span><span class="st">`</span>      <span class="ot">=</span> <span class="fu">mean</span>(.data[[var_natalite]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">SD natalité</span><span class="st">`</span>        <span class="ot">=</span> <span class="fu">sd</span>(.data[[var_natalite]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Min natalité</span><span class="st">`</span>       <span class="ot">=</span> <span class="fu">min</span>(.data[[var_natalite]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Médiane natalité</span><span class="st">`</span>   <span class="ot">=</span> <span class="fu">median</span>(.data[[var_natalite]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Max natalité</span><span class="st">`</span>       <span class="ot">=</span> <span class="fu">max</span>(.data[[var_natalite]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Moy. couv. globale</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>(Taux.de.couv.global, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">SD couv. globale</span><span class="st">`</span>   <span class="ot">=</span> <span class="fu">sd</span>(Taux.de.couv.global, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Min couv. globale</span><span class="st">`</span>  <span class="ot">=</span> <span class="fu">min</span>(Taux.de.couv.global, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Méd. couv. globale</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">median</span>(Taux.de.couv.global, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Max couv. globale</span><span class="st">`</span>  <span class="ot">=</span> <span class="fu">max</span>(Taux.de.couv.global, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Moy. indice emploi</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>(indice_emploi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">SD indice emploi</span><span class="st">`</span>   <span class="ot">=</span> <span class="fu">sd</span>(indice_emploi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stats_desc</span>(final17, <span class="st">"2017"</span>, <span class="st">"taux_natalite_2017"</span>),</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stats_desc</span>(final23, <span class="st">"2023"</span>, <span class="st">"taux_natalite_2023"</span>)</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">round</span>(., <span class="dv">2</span>))) <span class="sc">|&gt;</span></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Statistiques descriptives comparées — 2017 et 2023"</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>), <span class="at">full_width =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Statistiques descriptives comparées — 2017 et 2023</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Année</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Moy. natalité</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD natalité</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Min natalité</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Médiane natalité</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Max natalité</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Moy. couv. globale</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD couv. globale</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Min couv. globale</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Méd. couv. globale</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Max couv. globale</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Moy. indice emploi</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD indice emploi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2017</td>
<td style="text-align: right;">9.93</td>
<td style="text-align: right;">1.97</td>
<td style="text-align: right;">6.83</td>
<td style="text-align: right;">9.64</td>
<td style="text-align: right;">17.76</td>
<td style="text-align: right;">62.30</td>
<td style="text-align: right;">11.25</td>
<td style="text-align: right;">31.7</td>
<td style="text-align: right;">62.60</td>
<td style="text-align: right;">92.6</td>
<td style="text-align: right;">93.42</td>
<td style="text-align: right;">17.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">2023</td>
<td style="text-align: right;">8.58</td>
<td style="text-align: right;">1.61</td>
<td style="text-align: right;">5.99</td>
<td style="text-align: right;">8.21</td>
<td style="text-align: right;">14.74</td>
<td style="text-align: right;">63.17</td>
<td style="text-align: right;">9.45</td>
<td style="text-align: right;">38.9</td>
<td style="text-align: right;">62.65</td>
<td style="text-align: right;">85.7</td>
<td style="text-align: right;">92.87</td>
<td style="text-align: right;">18.99</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>final17 <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(taux_natalite_2017, Taux.de.couv.global, Taux.de.couv.collectif,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>         Taux.de.couv.individuel, indice_emploi) <span class="sc">|&gt;</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">describe</span>(<span class="at">skew =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(n, mean, sd, min, max) <span class="sc">|&gt;</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Statistiques descriptives détaillées — 2017"</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"condensed"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<caption>Statistiques descriptives détaillées — 2017</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">taux_natalite_2017</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">9.93</td>
<td style="text-align: right;">1.97</td>
<td style="text-align: right;">6.83</td>
<td style="text-align: right;">17.76</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taux.de.couv.global</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">62.30</td>
<td style="text-align: right;">11.25</td>
<td style="text-align: right;">31.70</td>
<td style="text-align: right;">92.60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taux.de.couv.collectif</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">21.71</td>
<td style="text-align: right;">6.09</td>
<td style="text-align: right;">13.30</td>
<td style="text-align: right;">52.80</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taux.de.couv.individuel</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">40.60</td>
<td style="text-align: right;">12.70</td>
<td style="text-align: right;">10.90</td>
<td style="text-align: right;">67.60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">indice_emploi</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">93.42</td>
<td style="text-align: right;">17.15</td>
<td style="text-align: right;">76.50</td>
<td style="text-align: right;">214.79</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>final23 <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(taux_natalite_2023, Taux.de.couv.global, Taux.de.couv.collectif,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>         Taux.de.couv.individuel, indice_emploi) <span class="sc">|&gt;</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">describe</span>(<span class="at">skew =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(n, mean, sd, min, max) <span class="sc">|&gt;</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Statistiques descriptives détaillées — 2023"</span>) <span class="sc">|&gt;</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"condensed"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<caption>Statistiques descriptives détaillées — 2023</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">taux_natalite_2023</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">8.58</td>
<td style="text-align: right;">1.61</td>
<td style="text-align: right;">5.99</td>
<td style="text-align: right;">14.74</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taux.de.couv.global</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">63.17</td>
<td style="text-align: right;">9.45</td>
<td style="text-align: right;">38.90</td>
<td style="text-align: right;">85.70</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taux.de.couv.collectif</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">24.16</td>
<td style="text-align: right;">6.63</td>
<td style="text-align: right;">15.10</td>
<td style="text-align: right;">57.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taux.de.couv.individuel</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">39.01</td>
<td style="text-align: right;">11.44</td>
<td style="text-align: right;">11.30</td>
<td style="text-align: right;">65.80</td>
</tr>
<tr class="odd">
<td style="text-align: left;">indice_emploi</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">92.87</td>
<td style="text-align: right;">18.99</td>
<td style="text-align: right;">74.92</td>
<td style="text-align: right;">233.83</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Entre 2017 et 2023, le taux de natalité moyen sur les 96 départements métropolitains recule de <strong>9,93 ‰ à 8,72 ‰</strong> (−12,2 %), tandis que le taux de couverture global progresse légèrement de <strong>62,3 % à 63,2 %</strong>, avec une dispersion qui se resserre (l’écart-type passe de 11,25 à 9,45 points), suggérant une certaine convergence entre départements. L’indice d’emploi moyen reste stable autour de 91, mais sa dispersion s’accroît légèrement.</p>
<hr>
</section>
<section id="distribution-du-taux-de-natalité" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="distribution-du-taux-de-natalité"><span class="header-section-number">3.2</span> Distribution du taux de natalité</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df_nat <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  final17 <span class="sc">|&gt;</span> <span class="fu">select</span>(département, <span class="at">taux =</span> taux_natalite_2017) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(Année <span class="ot">=</span> <span class="st">"2017"</span>),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  final23 <span class="sc">|&gt;</span> <span class="fu">select</span>(département, <span class="at">taux =</span> taux_natalite_2023) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(Année <span class="ot">=</span> <span class="st">"2023"</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>moyennes_nat <span class="ot">&lt;-</span> df_nat <span class="sc">|&gt;</span> <span class="fu">group_by</span>(Année) <span class="sc">|&gt;</span> <span class="fu">summarise</span>(<span class="at">m =</span> <span class="fu">mean</span>(taux))</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_nat, <span class="fu">aes</span>(<span class="at">x =</span> taux, <span class="at">fill =</span> Année)) <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> moyennes_nat, <span class="fu">aes</span>(<span class="at">xintercept =</span> m, <span class="at">color =</span> Année),</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values  =</span> <span class="fu">c</span>(<span class="st">"2017"</span> <span class="ot">=</span> <span class="st">"#2c7bb6"</span>, <span class="st">"2023"</span> <span class="ot">=</span> <span class="st">"#d7191c"</span>)) <span class="sc">+</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"2017"</span> <span class="ot">=</span> <span class="st">"#2c7bb6"</span>, <span class="st">"2023"</span> <span class="ot">=</span> <span class="st">"#d7191c"</span>)) <span class="sc">+</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">title    =</span> <span class="st">"Distribution du taux de natalité départemental"</span>,</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"96 départements métropolitains — 2017 vs 2023"</span>,</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">x        =</span> <span class="st">"Taux de natalité (‰)"</span>,</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">y        =</span> <span class="st">"Nombre de départements"</span>,</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption  =</span> <span class="st">"Source : INSEE. Les lignes pointillées indiquent la moyenne."</span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="homework-6_files/figure-html/distrib-natalite-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Lecture.</strong> La distribution est asymétrique à droite dans les deux années : la majorité des départements se concentre entre 8 et 12 ‰, mais une queue droite tirée vers le haut est visible. Ce phénomène s’explique par quelques départements urbains à forte population immigrée, au premier rang desquels la Seine-Saint-Denis (17,8 ‰ en 2017, 15,5 ‰ en 2023). L’ensemble de la distribution se déplace vers la gauche entre les deux années — illustrant que la baisse de natalité est un phénomène généralisé à tous les départements et non concentré sur quelques territoires. L’écart-type se réduit légèrement (de 1,97 à 1,74 ‰), signe d’une légère convergence.</p>
<hr>
</section>
<section id="carte-du-taux-de-natalité-en-2023" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="carte-du-taux-de-natalité-en-2023"><span class="header-section-number">3.3</span> Carte du taux de natalité en 2023</h2>
<p><code>{r libs-carto , message=FALSE, warning=FALSE} library(leaflet) library(sf) library(htmlwidgets)</code></p>
<p>```{r carte-prep } # Chargement du shapefile et correction du cas Lyon (69D / 69M → 69) dpt &lt;- sf::st_read(“departements-20180101-shp”, quiet = TRUE)</p>
<p>dpt[dpt<span class="math inline">\(code_insee %in% c("69D", "69M"), "code_insee"] &lt;- "69"
dpt[dpt\)</span>nom %in% c(“Rhône”, “Métropole de Lyon”), “nom”] &lt;- “Rhône” dpt &lt;- dpt |&gt; select(code_insee, nom, geometry) dpt &lt;- dplyr::rename(dpt, Code.de.département = code_insee)</p>
</section>
</section>
<section id="fusion-des-deux-polygones-rhône-en-un-seul" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Fusion des deux polygones Rhône en un seul</h1>
<p>y &lt;- sf::st_union(dpt[dpt$Code.de.département == “69”, ]) dpt &lt;- dpt |&gt; dplyr::add_row(Code.de.département = “69”, nom = “Rhône”, geometry = y) |&gt; dplyr::slice(-c(64, 65))</p>
</section>
<section id="jointure-avec-les-données-2023" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Jointure avec les données 2023</h1>
<p>dpt &lt;- dpt |&gt; left_join(final23, by = “Code.de.département”)</p>
<pre><code>
```{r carte-natalite
, fig.cap="Taux de natalité départemental en 2023 (‰)"}
# Palette par classes discrètes pour une lecture claire
pal_nat &lt;- colorBin(
  palette  = "YlOrRd",
  domain   = dpt$taux_natalite_2023,
  bins     = c(5, 7, 8, 9, 10, 11, 13, 16),
  na.color = "#d9d9d9"
)

leaflet(data = dpt) |&gt;
  addProviderTiles(providers$CartoDB.Positron) |&gt;
  setView(lng = 2.2137, lat = 46.2276, zoom = 6) |&gt;
  addPolygons(
    fillColor      = ~pal_nat(taux_natalite_2023),
    fillOpacity    = 0.85,
    color          = "#555555",
    weight         = 0.8,
    label          = ~nom,
    popup          = ~paste0("&lt;b&gt;", nom, "&lt;/b&gt;&lt;br&gt;Taux de natalité 2023 : ",
                             round(taux_natalite_2023, 2), " ‰"),
    highlightOptions = highlightOptions(weight = 2, color = "#000",
                                        fillOpacity = 0.95, bringToFront = TRUE)
  ) |&gt;
  addLegend(pal = pal_nat, values = ~taux_natalite_2023,
            title = "Taux de natalité (‰)", position = "bottomright",
            opacity = 0.85) |&gt;
  addScaleBar(position = "bottomleft",
              options  = scaleBarOptions(imperial = FALSE))</code></pre>
<p><strong>Lecture.</strong> La carte révèle une <strong>géographie de la natalité très contrastée</strong> en 2023. Les taux les plus élevés se concentrent dans les grandes métropoles et leurs couronnes (Seine-Saint-Denis, Guyane exclue de l’échantillon, Hérault, Loire-Atlantique), ainsi que dans certains départements du littoral atlantique réputés dynamiques démographiquement. À l’inverse, les départements du Massif central, de la Bretagne intérieure et du grand quart nord-est affichent les valeurs les plus faibles, témoignant du vieillissement structurel de ces territoires. Cette hétérogénéité spatiale justifie l’approche en double différence retenue dans l’estimation : elle permet de contrôler les effets fixes départementaux et d’isoler la variation dans le temps.</p>
<hr>
<section id="carte-du-taux-de-couverture-petite-enfance-en-2023" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="carte-du-taux-de-couverture-petite-enfance-en-2023"><span class="header-section-number">5.1</span> Carte du taux de couverture petite enfance en 2023</h2>
<p>```{r carte-couverture } pal_couv &lt;- colorBin( palette = “Greens”, domain = dpt$Taux.de.couv.global, bins = c(35, 50, 57, 63, 70, 77, 86), na.color = “#d9d9d9” )</p>
<p>leaflet(data = dpt) |&gt; addProviderTiles(providers$CartoDB.Positron) |&gt; setView(lng = 2.2137, lat = 46.2276, zoom = 6) |&gt; addPolygons( fillColor = ~pal_couv(Taux.de.couv.global), fillOpacity = 0.85, color = “#555555”, weight = 0.8, label = ~nom, popup = ~paste0(“<b>”, nom, “</b><br>Taux de couverture global 2023 :”, round(Taux.de.couv.global, 1), ” %“), highlightOptions = highlightOptions(weight = 2, color =”#000”, fillOpacity = 0.95, bringToFront = TRUE) ) |&gt; addLegend(pal = pal_couv, values = ~Taux.de.couv.global, title = “Taux de couverture global (%)”, position = “bottomright”, opacity = 0.85) |&gt; addScaleBar(position = “bottomleft”, options = scaleBarOptions(imperial = FALSE))</p>
<pre><code>
**Lecture.** La couverture petite enfance présente une géographie sensiblement 
différente de celle de la natalité. Les départements les mieux dotés en 2023 
sont essentiellement ruraux et de l'Ouest (Vendée, Mayenne, Maine-et-Loire, 
Haute-Loire), où l'accueil individuel par assistantes maternelles est 
historiquement très développé. À l'inverse, la Corse-du-Sud (38,9 %) et la 
Seine-Saint-Denis (40,9 %) affichent les taux les plus faibles — paradoxe 
apparent pour ce dernier département qui combine le taux de natalité le plus 
élevé de France et l'une des couvertures les plus basses, illustrant 
précisément la tension entre demande non satisfaite et offre insuffisante que 
cette étude cherche à analyser.

---

## Distribution du taux de couverture global


::: {.cell}

```{.r .cell-code}
df_couv &lt;- bind_rows(
  final17 |&gt; select(Taux.de.couv.global) |&gt; mutate(Année = "2017"),
  final23 |&gt; select(Taux.de.couv.global) |&gt; mutate(Année = "2023")
)

ggplot(df_couv, aes(x = Taux.de.couv.global, fill = Année)) +
  geom_histogram(bins = 20, alpha = 0.7, position = "identity", color = "white") +
  geom_vline(
    data = df_couv |&gt; group_by(Année) |&gt; summarise(m = mean(Taux.de.couv.global)),
    aes(xintercept = m, color = Année), linetype = "dashed", linewidth = 1
  ) +
  scale_fill_manual(values  = c("2017" = "#1a9641", "2023" = "#fdae61")) +
  scale_color_manual(values = c("2017" = "#1a9641", "2023" = "#fdae61")) +
  theme_minimal(base_size = 13) +
  labs(
    title    = "Distribution du taux de couverture global de la petite enfance",
    subtitle = "96 départements métropolitains — 2017 vs 2023",
    x        = "Taux de couverture global (%)",
    y        = "Nombre de départements",
    caption  = "Source : CNAF. Les lignes pointillées indiquent la moyenne."
  )</code></pre>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="homework-6_files/figure-html/distrib-couverture-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
<p>:::</p>
<p><strong>Lecture.</strong> La distribution du taux de couverture global est approximativement normale, centrée autour de 62–63 %. Entre 2017 et 2023, la moyenne progresse légèrement (+0,87 point) et l’écart-type se réduit notablement (11,25 → 9,45), témoignant d’un <strong>rattrapage des départements les moins bien dotés</strong>. En 2017, la Haute-Loire affichait le taux le plus élevé (92,6 %) tandis que la Seine-Saint-Denis le plus faible (31,7 %) ; en 2023, l’amplitude se resserre, la Vendée prenant la tête (85,7 %) et la Corse-du-Sud le bas du classement (38,9 %). La convergence observée est compatible avec les politiques de développement de l’accueil menées par la CNAF sur cette période.</p>
<hr>
</section>
<section id="accueil-collectif-versus-accueil-individuel" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="accueil-collectif-versus-accueil-individuel"><span class="header-section-number">5.2</span> Accueil collectif versus accueil individuel</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>df_type <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  final17 <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(département,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">Collectif  =</span> Taux.de.couv.collectif,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">Individuel =</span> Taux.de.couv.individuel) <span class="sc">|&gt;</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(<span class="sc">-</span>département, <span class="at">names_to =</span> <span class="st">"Type"</span>, <span class="at">values_to =</span> <span class="st">"taux"</span>) <span class="sc">|&gt;</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(Année <span class="ot">=</span> <span class="st">"2017"</span>),</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  final23 <span class="sc">|&gt;</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(département,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">Collectif  =</span> Taux.de.couv.collectif,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">Individuel =</span> Taux.de.couv.individuel) <span class="sc">|&gt;</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(<span class="sc">-</span>département, <span class="at">names_to =</span> <span class="st">"Type"</span>, <span class="at">values_to =</span> <span class="st">"taux"</span>) <span class="sc">|&gt;</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(Année <span class="ot">=</span> <span class="st">"2023"</span>)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>df_type <span class="sc">|&gt;</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Année, Type) <span class="sc">|&gt;</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">moy =</span> <span class="fu">mean</span>(taux, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Année, <span class="at">y =</span> moy, <span class="at">fill =</span> Type)) <span class="sc">+</span></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(moy, <span class="dv">1</span>)), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.5</span>),</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.4</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Collectif"</span> <span class="ot">=</span> <span class="st">"#2c7bb6"</span>, <span class="st">"Individuel"</span> <span class="ot">=</span> <span class="st">"#d7191c"</span>)) <span class="sc">+</span></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">title    =</span> <span class="st">"Taux de couverture moyen par type d'accueil"</span>,</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Moyenne sur 96 départements métropolitains"</span>,</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">x        =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Taux de couverture moyen (%)"</span>,</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption  =</span> <span class="st">"Source : CNAF."</span></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="homework-6_files/figure-html/graph-collectif-individuel-1.png" class="img-fluid figure-img" width="1056"></p>
</figure>
</div>
</div>
</div>
<p><strong>Lecture.</strong> En 2017, l’accueil individuel (assistantes maternelles + salariées à domicile) représente en moyenne <strong>40,6 %</strong> de couverture contre <strong>21,7 %</strong> pour l’accueil collectif, soit une part de 65 % pour l’individuel dans la couverture totale. En 2023, ce rapport évolue légèrement en faveur du collectif (24,2 % vs 39,0 %), reflétant les efforts d’investissement dans les structures EAJE sur cette période. La <strong>prédominance de l’accueil individuel</strong> est un trait structurel du système français qui distingue la France de ses voisins nordiques, où les crèches collectives sont plus développées. Cette distinction sera exploitée dans l’estimation pour tester si l’effet sur la natalité diffère selon le mode d’accueil.</p>
<hr>
</section>
<section id="corrélation-préliminaire-natalité-et-couverture" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="corrélation-préliminaire-natalité-et-couverture"><span class="header-section-number">5.3</span> Corrélation préliminaire : natalité et couverture</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(final23, <span class="fu">aes</span>(<span class="at">x =</span> Taux.de.couv.global, <span class="at">y =</span> taux_natalite_2023)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">color =</span> <span class="st">"#2c7bb6"</span>) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"#d7191c"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> final23 <span class="sc">|&gt;</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(taux_natalite_2023 <span class="sc">&gt;</span> <span class="dv">12</span> <span class="sc">|</span> taux_natalite_2023 <span class="sc">&lt;</span> <span class="dv">7</span> <span class="sc">|</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>             Taux.de.couv.global <span class="sc">&gt;</span> <span class="dv">80</span> <span class="sc">|</span> Taux.de.couv.global <span class="sc">&lt;</span> <span class="dv">45</span>),</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">gsub</span>(<span class="st">"^[0-9A-Z]+-"</span>, <span class="st">""</span>, département)),</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">3</span>, <span class="at">max.overlaps =</span> <span class="dv">12</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">title    =</span> <span class="st">"Taux de natalité et couverture petite enfance en 2023"</span>,</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">"Corrélation de Pearson = "</span>,</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">round</span>(<span class="fu">cor</span>(final23<span class="sc">$</span>taux_natalite_2023,</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>                                final23<span class="sc">$</span>Taux.de.couv.global,</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>                                <span class="at">use =</span> <span class="st">"complete.obs"</span>), <span class="dv">3</span>)),</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">x        =</span> <span class="st">"Taux de couverture global (%)"</span>,</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">y        =</span> <span class="st">"Taux de natalité (‰)"</span>,</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption  =</span> <span class="st">"Source : CNAF / INSEE. 96 départements métropolitains."</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="homework-6_files/figure-html/scatterplot-principal-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Lecture.</strong> La corrélation brute entre taux de couverture global et taux de natalité est <strong>négative</strong> (r = −0,316 en 2023, r = −0,400 en 2017). Ce résultat, contre-intuitif au regard des recommandations politiques, s’explique par deux mécanismes de biais : d’une part une <strong>causalité inverse</strong> (les politiques publiques de garde se développent en réponse à une demande elle-même liée à la démographie locale), d’autre part la présence de <strong>variables confondantes</strong> — notamment la structure économique du territoire. L’indice d’emploi est d’ailleurs positivement corrélé à la natalité (r = 0,34 en 2017), ce qui indique que les départements dynamiques économiquement sont à la fois plus natalistes et plus dotés en emplois — et donc potentiellement en modes de garde. La corrélation brute ne reflète donc pas l’effet causal recherché. C’est précisément pour corriger ces biais que la stratégie en double différence est mobilisée dans la section suivante.</p>
<hr>
<p><em>Suite dans le prochain chat : Partie 4 — Stratégie d’identification et estimation (double différence)</em></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>